learning_log/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from learning_log import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('learning_logs.urls',  namespace='learning_logs')),
    url(r'^users/', include('users.urls', namespace='users'))
]

learning_logs/urls.py
"""define url pattern of learning_logs"""

from django.conf.urls import url

from . import views

urlpatterns = [
    # homepage
    url(r'^$', views.index, name='index'),

    # show all topics
    url(r'^topics/$', views.topics, name='topics'),

    # show a specific topic and its contents
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),

    # add new topic
    url(r'^new_topic/$', views.new_topic, name='new_topic'),

    # add new entry
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),

    # edit entry
    url(r'edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views


urlpatterns = [
    # login page
    url(r'^login/$', login, {'template_name':'users/login.html'}, name='login'),

    # log out
    url(r'^logout/$', views.logout_view, name='logout'),

    # register
    url(r'^register/$', views.register, name='register')
]

learning_logs/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Topic(models.Model):
    """ the topics of users' learning """
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    def __str__(self):
        """ return strings to express models """
        return self.text


class Entry(models.Model):
    """specific knowledge about one topic"""
    topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)
    
    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
        """return strings of model"""
        if len(self.text) > 50:
            return self.text[:50] + '...'
        else:
            return self.text

users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text', ]
        labels = {'text':''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text': forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


# Create your views here.


def index(request):
    """homepage of learning_logs"""
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    """show all topics"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    """show a specific topic and its contents"""
    topic = get_object_or_404(Topic, id=topic_id)
    # make sure that the requested topic belongs to the owner
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """add new topic"""
    if request.method != 'POST':
        # if there is no need to submit data: create a new form
        form = TopicForm()
    else:
        # there are some data submitted by post, handle the data
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """add new entry"""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))

    context = {"form": form, "topic":topic}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """edit entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[entry.topic.id]))

    context = {'entry':entry, 'form':form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def logout_view(request):
    """let users log out"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))


def register(request):
    """user register"""
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))

    context = {'form':form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">

      <title>Learning Log</title>

      {% bootstrap_css %}
      {% bootstrap_javascript %}
  </head>

<body>

<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'learning_logs:topics' %}">Topics <span class="sr-only">(current)</span></a></li>
      </ul>

       <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li><a>Hello, {{ user.username }}.</a></li>
            <li><a href="{% url 'users:logout' %}">logout</a></li>
          {% else %}
            <li><a href="{% url 'users:register' %}">register</a></li>
            <li><a href="{% url 'users:login' %}">log in</a></li>
          {% endif %}
        </ul>
      </div>


    </div>
  </nav>

  <div class="container">

    <div class="page-header">
      {% block header %}{% endblock header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>

  </div><!-- /container-->


</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
    <h2>Edit entry:</h2>
{% endblock header %}
{% block content %}

<form action="{% url 'learning_logs:edit_entry' entry.id %}" method="POST" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}

  {% buttons %}
    <button name="submit" class="btn btn-primary">submit</button>
  {% endbuttons %}


</form>


{% endblock content %}
</body>
</html>

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <div class="jumbotron">
    <h1>Track your learning.</h1>
  </div>
{% endblock header %}

{% block content %}
  <h2>
    <a href="{% url 'users:register' %}">Resister an account</a> to
  make your own Learning Log, and list the topics your're learning about.
  </h2>
  <h2>
    Whenever you learn something new about a topic, make an entry summarizing what you've learned.
  </h2>

{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
    <h2>Add new entry</h2>
{% endblock header %}

{% block content %}

<form action="{% url 'learning_logs:new_entry' topic.id %}" method='POST' class="form">
  {% csrf_token %}
  {% bootstrap_form form %}

  {% buttons %}
  <button name="submit" class="btn btn-primary">submit</button>
  {% endbuttons %}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

</head>
<body>


{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add a new topic:</h2>
{% endblock header %}
{% block content %}

<p>Add a new topic:</p>

<form action="{% url 'learning_logs:new_topic' %}" method='POST' class="form">
  {% csrf_token %}
  {% bootstrap_form form %}

  {% buttons %}
      <button name="submit" class="btn btn-primary">add topic</button>
  {% endbuttons %}
</form>


{% endblock content %}

</body>
</html>

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
  </p>

    {% for entry in entries %}
        <div class="panel panel-default">
          <div class="panel-heading">
          <h3>
            {{ entry.date_added|date:'M d, Y H:i' }}
            <small>
               <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a>
            </small>
          </h3>
          </div>
          <div class="panel-body">
             <p>{{ entry.text|linebreaks }}</p>
          </div>
         </div>

        {% empty %}
          <li>No entries have been added yet.</li>
        {% endfor %}




{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <h1>Topics</h1>
{% endblock header %}

{% block content %}


    <ul>
        {% for topic in topics %}
          <li>
            <h3>
              <a href="{% url 'learning_logs:topic' topic.id%}">{{ topic }}</a>
            </h3>
          </li>
        {% empty %}
          <li>No topics have been added yet.</li>
        {% endfor %}
    </ul>

  <h3><a href="{% url 'learning_logs:new_topic' %}">Add new topic</a></h3>
{% endblock content %}

users/templates/users/login.html
<!DOCTYPE html>
{% extends 'learning_logs/base.html' %}

{% load bootstrap3 %}

{% block header %}
  <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}

<form action="{% url 'users:login' %}"  method='post' class="form">
  {% csrf_token %} }
  {% bootstrap_form form %}

  {% buttons %}
    <button name="submit" class="btn btn-primary">log in</button>
  {% endbuttons %}

 <input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>

</form>

{% endblock content %}

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>

<body>
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}
{% block header %}
  <h2>Register your account.</h2>
{% endblock header %}

{% block content %}

<form action="{% url 'users:register' %}" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}

  {% buttons %}
    <button name="submit" class="btn btn-primary">sign up</button>
  {% endbuttons %}

<input type="hidden" name="next" value="{% url 'learning_logs:index' %}"/>
</form>
{% endblock content %}

</body>
</html>